#ifndef __ABR_STM_TYPES_H__
#define __ABR_STM_TYPES_H__

#include "abrstm/export.h"

/** @addtogroup abrstm_api_types

*/

/** @defgroup abrstm_api_types_modules Module defines
@ingroup abrstm_api_types
Each module within the library is individually defined by a name and id.
These can be used to target logging for particular modules and to identify the source of errors.
When setting logging, the MODULEID values can be bitwised or-ed.

Note that not all modules are necessarily exposed via a public API, even though they appear here.

@{
*/
#define ABR_STM_LIBRARY       "abrstm" /**< The name of the library. */
#define ABR_STM_MODULE_LIB    "lib" /**< The lib module name. */
#define ABR_STM_MODULE_STM    "stm" /**< The stm module name. */
#define ABR_STM_MODULE_TKN    "tkn" /**< The tkn module name.*/
#define ABR_STM_MODULE_ERRFN  "errfn" /**< The errfn module name.*/

#define ABR_STM_MODULEID_LIB    0x00000001UL /**< The lib module id. */
#define ABR_STM_MODULEID_STM    0x00000002UL /**< The stm module id. */
#define ABR_STM_MODULEID_TKN    0x00000004UL /**< The tkn module id. */
#define ABR_STM_MODULEID_ERRFN  0x00000008UL /**< The errfn module id. */

/**
The ABR_STM_INIT_... defines are used to control the initialisation that takes place. Currently
only ABR_STM_INIT_ALL is defined. 
*/
#define ABR_STM_INIT_ALL 0xffff

/** @} */

#ifdef __cplusplus
extern "C" {
#endif 

/** @defgroup abrstm_api_types_config Configuration Values
@ingroup abrstm_api_types
These values can optionally be used to access variables in the configuration file.

@{
*/

/**
This is the configuration variable name for the network timeout to use instead of @ref abr_CfgN_Base_Http_Timeout - independent of servicetype.
*/
ABR_STM_EXPORT_VAR const char abr_CfgN_Stm_HttpTimeout[];
/**
This is the configuration variable name for the network connect timeout to use instead of @ref abr_CfgN_Base_Http_TimeoutConnect - independent of servicetype.
*/
ABR_STM_EXPORT_VAR const char abr_CfgN_Stm_HttpTimeoutConnect[];
/**
This is the configuration variable name for the URL of the STM service.
*/
ABR_STM_EXPORT_VAR const char abr_CfgN_Stm_Url[];
/**
This is the configuration variable name for the URL of relying party.
*/
ABR_STM_EXPORT_VAR const char abr_CfgN_Stm_RelyingParty[];
/**
This is the configuration variable name for the STM template directory.
*/
ABR_STM_EXPORT_VAR const char abr_CfgN_Stm_Template_Dir[];
/**
This is the configuration variable name for the STM template file name.
*/
ABR_STM_EXPORT_VAR const char abr_CfgN_Stm_Template_File[];

/** @} */

#ifdef __cplusplus
}
#endif 

/** @defgroup abrstm_api_types_errcodes Error codes
@ingroup abrstm_api_types
All errors are encapsulated in STM specific errors.
For the underlying error, use abr_err_inner() to retrieve nested errors and their details.


@{
*/

#define ABR_STM_ERR_MIN 13000 /**< The mimimum error number. */
#define ABR_STM_ERR_GENERAL (ABR_STM_ERR_MIN+1)  /**< For errors not specified below. */
#define ABR_STM_ERR_NETSENDER (ABR_STM_ERR_MIN+2) /**< A SOAP fault generated by the sender, not including service unavailable. */
#define ABR_STM_ERR_NETRECEIVER (ABR_STM_ERR_MIN+3) /**< A SOAP fault generated by the receiver, not including service unavailable. */
#define ABR_STM_ERR_NETUNAVAILABLE (ABR_STM_ERR_MIN+4) /**< A SOAP fault where the remote service is unavailable. */
#define ABR_STM_ERR_NETCOMMS (ABR_STM_ERR_MIN+5) /**< A general network error has occurred, not including timeouts. */
#define ABR_STM_ERR_NETTIMEOUT (ABR_STM_ERR_MIN+6)  /**< A network time has occured trying to connect to a remote service. */
#define ABR_STM_ERR_MAX (ABR_STM_ERR_MIN+200) /**< The maximum error number. */
/** @} */

#endif /*__ABR_STM_TYPES_H__*/
